version: "3.4"
services:

  # 9 months old
  kong-admin-ui:
    image: pocketdigi/kong-admin-ui:0.5.3
    ports:
      - 8899:80

  # 2 years old
  konga:
    image: pantsel/konga:0.14.9
    environment:
      NO_AUTH: true
      NODE_ENV: production

    ports: 
      - 1337:1337

  # 3 years old / not working anymore
  # kong-dashboard:
  #   image: pgbi/kong-dashboard:v3.5.0
  #   command: start --kong-url http://kong:8001
  #   ports:
  #     - 8080:8080

  # 4 years old / not working anymore
  # kongui:
  #   image: tfarla/kongui:latest

  kong:
    build:
      context: .
      dockerfile: kong.dockerfile
    command: kong start
    depends_on:
      - kong-bootstrap
    restart: on-failure
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "db"
      KONG_PG_DATABASE: "kong"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"
      KONG_PROXY_ACCESS: /dev/stdout
      KONG_PROXY_ERRROR: /dev/sterr
      KONG_ADMIN_ACCESS: /dev/stdout
      KONG_ADMIN_ERRROR: /dev/sterr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    volumes:
      - ./config:/opt/kong
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10

  kong-bootstrap:
    build:
      context: .
      dockerfile: kong.dockerfile
    command: kong migrations bootstrap
    depends_on:
      - db
    restart: on-failure
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "db"
      KONG_PG_DATABASE: "kong"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"

  db:
    image: postgres:14.2-alpine3.15
    restart: unless-stopped
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_PASSWORD: "kong"
      POSTGRES_DB: "kong"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 5
    volumes:
      - kong_data:/var/lib/postgresql/data

networks:
  default:
    name: kong-net
volumes:
  kong_data: 